language: java
jdk:
   - oraclejdk8
script: ant build

addons:
  sonarcloud:
    organization: "cwjung479-github" # the key of the org you chose at step #3
    token:
      secure: SONAR_TOKEN # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
